package com.entities;
// Generated 7 avr. 2018 11:52:32 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Attendance generated by hbm2java
 */
@Entity
@Table(name = "attendance", catalog = "java_project")
public class Attendance implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private AttendanceId id;
	private String state;

	public Attendance() {
	}

	public Attendance(AttendanceId id, String state) {
		this.id = id;
		this.state = state;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "nurseryName", column = @Column(name = "nurseryName", nullable = false, length = 30)),
			@AttributeOverride(name = "contractId", column = @Column(name = "contractId", nullable = false)),
			@AttributeOverride(name = "attendanceDate", column = @Column(name = "attendanceDate", nullable = false, length = 10)),
			@AttributeOverride(name = "halfday", column = @Column(name = "halfday", nullable = false, length = 9)) })
	public AttendanceId getId() {
		return this.id;
	}

	public void setId(AttendanceId id) {
		this.id = id;
	}

	@Column(name = "state", nullable = false, length = 19)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

}
