package com.entities;
// Generated 7 avr. 2018 11:52:32 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract", catalog = "java_project")
public class Contract implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private ContractId id;
	private Date beginDate;
	private Date endDate;
	private double pricePerHour;
	private String email;
	private String phoneNumber;
	private String contractType;
	private Integer childId;

	public Contract() {
	}

	public Contract(ContractId id, Date beginDate, Date endDate, double pricePerHour, String phoneNumber,
			String contractType) {
		this.id = id;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.pricePerHour = pricePerHour;
		this.phoneNumber = phoneNumber;
		this.contractType = contractType;
	}

	public Contract(ContractId id, Date beginDate, Date endDate, double pricePerHour, String email, String phoneNumber,
			String contractType, Integer childId) {
		this.id = id;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.pricePerHour = pricePerHour;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.contractType = contractType;
		this.childId = childId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contractId", column = @Column(name = "contractId", nullable = false)),
			@AttributeOverride(name = "nurseryName", column = @Column(name = "nurseryName", nullable = false, length = 30)) })
	public ContractId getId() {
		return this.id;
	}

	public void setId(ContractId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "beginDate", nullable = false, length = 10)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endDate", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "pricePerHour", nullable = false, precision = 22, scale = 0)
	public double getPricePerHour() {
		return this.pricePerHour;
	}

	public void setPricePerHour(double pricePerHour) {
		this.pricePerHour = pricePerHour;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phoneNumber", nullable = false, length = 10)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "contractType", nullable = false, length = 9)
	public String getContractType() {
		return this.contractType;
	}

	public void setContractType(String contractType) {
		this.contractType = contractType;
	}

	@Column(name = "childId")
	public Integer getChildId() {
		return this.childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

}
