package com.entities;
// Generated 7 avr. 2018 11:52:32 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractId generated by hbm2java
 */
@Embeddable
public class ContractId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int contractId;
	private String nurseryName;

	public ContractId() {
	}

	public ContractId(int contractId, String nurseryName) {
		this.contractId = contractId;
		this.nurseryName = nurseryName;
	}

	@Column(name = "contractId", nullable = false)
	public int getContractId() {
		return this.contractId;
	}

	public void setContractId(int contractId) {
		this.contractId = contractId;
	}

	@Column(name = "nurseryName", nullable = false, length = 30)
	public String getNurseryName() {
		return this.nurseryName;
	}

	public void setNurseryName(String nurseryName) {
		this.nurseryName = nurseryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractId))
			return false;
		ContractId castOther = (ContractId) other;

		return (this.getContractId() == castOther.getContractId())
				&& ((this.getNurseryName() == castOther.getNurseryName())
						|| (this.getNurseryName() != null && castOther.getNurseryName() != null
								&& this.getNurseryName().equals(castOther.getNurseryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContractId();
		result = 37 * result + (getNurseryName() == null ? 0 : this.getNurseryName().hashCode());
		return result;
	}

}
