package com.entities;
// Generated 7 avr. 2018 11:52:32 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OffdayId generated by hbm2java
 */
@Embeddable
public class OffdayId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private String nurseryName;
	private Date offDate;
	private String halfday;

	public OffdayId() {
	}

	public OffdayId(String nurseryName, Date offDate, String halfday) {
		this.nurseryName = nurseryName;
		this.offDate = offDate;
		this.halfday = halfday;
	}

	@Column(name = "nurseryName", nullable = false, length = 30)
	public String getNurseryName() {
		return this.nurseryName;
	}

	public void setNurseryName(String nurseryName) {
		this.nurseryName = nurseryName;
	}

	@Column(name = "offDate", nullable = false, length = 10)
	public Date getOffDate() {
		return this.offDate;
	}

	public void setOffDate(Date offDate) {
		this.offDate = offDate;
	}

	@Column(name = "halfday", nullable = false, length = 9)
	public String getHalfday() {
		return this.halfday;
	}

	public void setHalfday(String halfday) {
		this.halfday = halfday;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OffdayId))
			return false;
		OffdayId castOther = (OffdayId) other;

		return ((this.getNurseryName() == castOther.getNurseryName()) || (this.getNurseryName() != null
				&& castOther.getNurseryName() != null && this.getNurseryName().equals(castOther.getNurseryName())))
				&& ((this.getOffDate() == castOther.getOffDate()) || (this.getOffDate() != null
						&& castOther.getOffDate() != null && this.getOffDate().equals(castOther.getOffDate())))
				&& ((this.getHalfday() == castOther.getHalfday()) || (this.getHalfday() != null
						&& castOther.getHalfday() != null && this.getHalfday().equals(castOther.getHalfday())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNurseryName() == null ? 0 : this.getNurseryName().hashCode());
		result = 37 * result + (getOffDate() == null ? 0 : this.getOffDate().hashCode());
		result = 37 * result + (getHalfday() == null ? 0 : this.getHalfday().hashCode());
		return result;
	}

}
